In [1]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define the Vocabulary the size
voc_size=10000

In [5]:
## One Hot Representation
one_hot_representation=[one_hot(words,voc_size)for words in sent]
one_hot_representation

[[3356, 2917, 5715, 719],
 [3356, 2917, 5715, 5275],
 [3356, 2132, 5715, 7928],
 [7742, 4077, 4494, 5567, 2081],
 [7742, 4077, 4494, 5567, 1537],
 [8244, 3356, 3435, 5715, 551],
 [760, 7264, 1539, 5567]]

In [6]:
## Word Embedding Representation

import tensorflow
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np
sent_length=8
embedded_docs=pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3356 2917 5715  719]
 [   0    0    0    0 3356 2917 5715 5275]
 [   0    0    0    0 3356 2132 5715 7928]
 [   0    0    0 7742 4077 4494 5567 2081]
 [   0    0    0 7742 4077 4494 5567 1537]
 [   0    0    0 8244 3356 3435 5715  551]
 [   0    0    0    0  760 7264 1539 5567]]


In [8]:
## Feature Representation
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Movie_Review_sentiment_analysis_Project\venv1\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step


array([[[ 2.10178383e-02, -3.72326151e-02,  3.56108658e-02,
          5.58537245e-03, -3.64996307e-02, -1.79908164e-02,
          1.30536444e-02, -3.21693197e-02,  2.66169347e-02,
          3.82671393e-02],
        [ 2.10178383e-02, -3.72326151e-02,  3.56108658e-02,
          5.58537245e-03, -3.64996307e-02, -1.79908164e-02,
          1.30536444e-02, -3.21693197e-02,  2.66169347e-02,
          3.82671393e-02],
        [ 2.10178383e-02, -3.72326151e-02,  3.56108658e-02,
          5.58537245e-03, -3.64996307e-02, -1.79908164e-02,
          1.30536444e-02, -3.21693197e-02,  2.66169347e-02,
          3.82671393e-02],
        [ 2.10178383e-02, -3.72326151e-02,  3.56108658e-02,
          5.58537245e-03, -3.64996307e-02, -1.79908164e-02,
          1.30536444e-02, -3.21693197e-02,  2.66169347e-02,
          3.82671393e-02],
        [ 1.91893466e-02, -2.97654402e-02,  3.73915546e-02,
          9.39751789e-03,  1.56998970e-02, -4.72020172e-02,
          4.07327302e-02,  2.59750597e-02, -1.349229