In [14]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [16]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [17]:
## define the Vocabulary the size
voc_size=10000

In [20]:
## One Hot Representation
one_hot_representation=[one_hot(words,voc_size)for words in sent]
one_hot_representation

[[2547, 7571, 5648, 8132],
 [2547, 7571, 5648, 7329],
 [2547, 2825, 5648, 8576],
 [4234, 2715, 757, 5428, 2208],
 [4234, 2715, 757, 5428, 3514],
 [9278, 2547, 2241, 5648, 8456],
 [3912, 4906, 4092, 5428]]

In [23]:
## Word Embedding Representation

import tensorflow
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np
sent_length=8
embedded_docs=pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2547 7571 5648 8132]
 [   0    0    0    0 2547 7571 5648 7329]
 [   0    0    0    0 2547 2825 5648 8576]
 [   0    0    0 4234 2715  757 5428 2208]
 [   0    0    0 4234 2715  757 5428 3514]
 [   0    0    0 9278 2547 2241 5648 8456]
 [   0    0    0    0 3912 4906 4092 5428]]


In [25]:
## Feature Representation
dim=10

In [26]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 154ms/step


array([[[ 0.02587384,  0.02116295,  0.01088617, -0.03592562,
         -0.04042912, -0.04580135,  0.03650352, -0.04325303,
         -0.00167348,  0.03055171],
        [ 0.02587384,  0.02116295,  0.01088617, -0.03592562,
         -0.04042912, -0.04580135,  0.03650352, -0.04325303,
         -0.00167348,  0.03055171],
        [ 0.02587384,  0.02116295,  0.01088617, -0.03592562,
         -0.04042912, -0.04580135,  0.03650352, -0.04325303,
         -0.00167348,  0.03055171],
        [ 0.02587384,  0.02116295,  0.01088617, -0.03592562,
         -0.04042912, -0.04580135,  0.03650352, -0.04325303,
         -0.00167348,  0.03055171],
        [-0.00954735, -0.04742479, -0.01982504, -0.01921876,
          0.02144418, -0.02219873, -0.04645871, -0.04861375,
         -0.04916892, -0.03659917],
        [ 0.02640999, -0.04857944,  0.04570656, -0.03586842,
         -0.03588607,  0.01649096, -0.00193025, -0.02198167,
         -0.02962157,  0.01996535],
        [ 0.03158773,  0.04036883, -0.03880373,  0.0

In [31]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 65ms/step


array([[ 0.02587384,  0.02116295,  0.01088617, -0.03592562, -0.04042912,
        -0.04580135,  0.03650352, -0.04325303, -0.00167348,  0.03055171],
       [ 0.02587384,  0.02116295,  0.01088617, -0.03592562, -0.04042912,
        -0.04580135,  0.03650352, -0.04325303, -0.00167348,  0.03055171],
       [ 0.02587384,  0.02116295,  0.01088617, -0.03592562, -0.04042912,
        -0.04580135,  0.03650352, -0.04325303, -0.00167348,  0.03055171],
       [ 0.02587384,  0.02116295,  0.01088617, -0.03592562, -0.04042912,
        -0.04580135,  0.03650352, -0.04325303, -0.00167348,  0.03055171],
       [-0.00954735, -0.04742479, -0.01982504, -0.01921876,  0.02144418,
        -0.02219873, -0.04645871, -0.04861375, -0.04916892, -0.03659917],
       [ 0.02640999, -0.04857944,  0.04570656, -0.03586842, -0.03588607,
         0.01649096, -0.00193025, -0.02198167, -0.02962157,  0.01996535],
       [ 0.03158773,  0.04036883, -0.03880373,  0.03595343,  0.02330009,
         0.03374124, -0.03428835, -0.00737494